-- Battery QC centralized Supabase schema
-- Run this entire script in Supabase Dashboard -> SQL Editor.

create table if not exists public.bqc_records (
  id text primary key,
  store_key text not null,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by text
);

create index if not exists idx_bqc_records_store_created
  on public.bqc_records (store_key, created_at);

create index if not exists idx_bqc_records_updated_at
  on public.bqc_records (updated_at desc);

create table if not exists public.bqc_audit_log (
  id bigint generated by default as identity primary key,
  username text,
  role text,
  action text not null,
  store_key text,
  record_id text,
  created_at timestamptz not null default now(),
  ip text,
  details jsonb
);

create index if not exists idx_bqc_audit_created
  on public.bqc_audit_log (created_at desc);

create index if not exists idx_bqc_audit_store
  on public.bqc_audit_log (store_key, created_at desc);

-- The application server uses the Supabase secret key and performs authorization itself.
-- Keep these tables inaccessible to anonymous/authenticated browser clients.
alter table public.bqc_records enable row level security;
alter table public.bqc_audit_log enable row level security;

-- No public policies are intentionally created here.
-- The server's secret key bypasses RLS and must NEVER be exposed to browsers.
